# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
     parcelorder.class: AppBundle\Entity\ParcelOrder
     postman.class: AppBundle\Entity\Postman

services:
    parcelorder_form.handler:
        class: AppBundle\Handler\ParcelorderFormHandler
        arguments: ['@doctrine.orm.entity_manager', %parcelorder.class%, '@form.factory', 'AppBundle\Form\ParcelorderType']
    postman_form.handler:
        class: AppBundle\Handler\PostmanFormHandler
        arguments: ['@doctrine.orm.entity_manager', %postman.class%, '@form.factory', 'AppBundle\Form\PostmanType']
