# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
     parcelorder.class: AppBundle\Entity\ParcelOrder

services:
     parcelorder_form.handler:
         class: AppBundle\Handler\ParcelorderFormHandler
         arguments: ['@doctrine.orm.entity_manager', %parcelorder.class%, '@form.factory', 'AppBundle\Form\ParcelorderType']
